[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"
PORT = "3000"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 100
healthcheckInterval = 30

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x"]

[phases.install]
cmds = ["npm ci", "npm install -g terser"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[[services]]
internalPort = 3000
processes = ["npm run start"]

[services.web]
internalPort = 3000