[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-8_x", "typescript"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"

[[services]]
internalPort = 3000
processes = ["npm run preview"]
